FROM golang:1.11.3
ARG version=1.0.5
ARG arch=amd64

# Install required build packages
RUN apt-get update && apt-get install -y git protobuf-compiler curl

# Install go tools
RUN go get github.com/gogo/protobuf/protoc-gen-gogo && \
    go get github.com/gogo/protobuf/protoc-gen-gofast && \
    go get github.com/gogo/protobuf/protoc-gen-gogofaster && \
    go get golang.org/x/tools/cmd/goimports && \
    go get github.com/grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway && \
    go get github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger && \
    go get github.com/golang/protobuf/protoc-gen-go && \
    go get github.com/jessevdk/go-assets-builder
