FROM golang:1.12.9-alpine AS protoinstall

# Install protoc 3.6
RUN apk add -u unzip
ADD https://github.com/protocolbuffers/protobuf/releases/download/v3.6.1/protoc-3.6.1-linux-x86_64.zip /tmp/protoc.zip
RUN cd /usr/local/ && unzip /tmp/protoc.zip

# Actual build image
FROM golang:1.12.9
ARG version=1.0.5
ARG arch=amd64
ARG TOKEN

# Install required build packages
RUN apt-get install -y git curl
COPY --from=protoinstall /usr/local/bin/protoc /usr/local/bin/

RUN git config --global "url.https://${TOKEN}@github.com/arangodb-managed/.insteadOf" "https://github.com/arangodb-managed/"
RUN git config --global --list 

ENV GO111MODULE=on

# Install go tools
RUN \
	go get github.com/arangodb-managed/protoc-gen-ts/cmd/protoc-gen-ts && \
    go get github.com/gogo/protobuf/protoc-gen-gogo && \
    go get github.com/gogo/protobuf/protoc-gen-gofast && \
    go get github.com/gogo/protobuf/protoc-gen-gogofaster && \
    go get golang.org/x/tools/cmd/goimports && \
    go get github.com/grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway && \
    go get github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger && \
    go get github.com/golang/protobuf/protoc-gen-go && \
    go get github.com/pseudomuto/protoc-gen-doc/cmd/protoc-gen-doc
